//! Mobile FFI wrapper over the pdf-core engine (Android via UniFFI).
//! pdf-core 引擎的移动端 FFI 包装（安卓经 UniFFI 生成 Kotlin 绑定）。
//!
//! This crate owns every mobile adaptation so the engine stays untouched:
//! the DTO mirror of the wire models, the 8-variant mobile error mirror
//! (the engine's 11-code taxonomy minus the desktop-shell codes
//! Io/Opener/Config, which collapse into [`FfiError::Engine`]), the cancel
//! handle, the progress callback, and the 512 MiB mobile input pre-check.
//! Kotlin bindings are generated by `scripts/gen-android-bindings.sh` and
//! committed under `android/app/src/main/uniffi/` — same discipline as the
//! desktop `frontend/src/lib/bindings.ts`.
//! 本 crate 收拢全部移动适配，引擎零改动：DTO 镜像、错误镜像、取消句柄、
//! 进度回调与 512 MiB 移动输入预检；绑定生成入库，纪律同 bindings.ts。

uniffi::setup_scaffolding!("pdfcompressor");

mod api;
mod cancel;
mod dto;
mod error;

pub use api::{
    analyze, build_features, compress, compress_to_target, max_mobile_input_bytes, ping,
    preset_defaults, FfiProgress, FfiProgressUpdate, MAX_MOBILE_INPUT_BYTES,
};
pub use cancel::FfiCancelHandle;
pub use dto::{
    FfiAnalysis, FfiBuildFeatures, FfiCompressResult, FfiNotice, FfiPresetProfile, FfiSettings,
};
pub use error::FfiError;
