//! Deterministic fixture builders shared by the integration tests, the
//! criterion benchmarks, and the examples.
//! 确定性夹具生成器 — 集成测试、criterion 基准与示例共用。
//!
//! Enabled via the `testutil` feature, which is turned on by this crate's
//! dev-dependency on itself — normal (non-dev) builds never compile it.
//! 通过 testutil 特性启用（由本 crate 对自身的 dev-dependency 打开），
//! 正常构建不会编译本模块。

use std::io::Cursor;

use image::{codecs::jpeg::JpegEncoder, DynamicImage, Rgb, RgbImage};

/// Gradient plus deterministic noise: behaves like a photograph under JPEG
/// (poorly compressible at high quality) while staying reproducible for a
/// given `seed`.
pub fn deterministic_rgb_image(width: u32, height: u32, seed: u32) -> RgbImage {
    let mut image = RgbImage::new(width, height);
    let mut state: u32 = seed;

    for y in 0..height {
        for x in 0..width {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            let noise = ((state >> 24) & 0xFF) as i32 - 128;
            let channel = |value: u32, span: u32| (value.saturating_mul(255) / span) as i32;
            let red = channel(x, width.max(1));
            let green = channel(y, height.max(1));
            let blue = channel(x + y, width.saturating_add(height).max(1));
            let components = [
                (red + noise).clamp(0, 255) as u8,
                (green + noise).clamp(0, 255) as u8,
                (blue + noise).clamp(0, 255) as u8,
            ];
            image.put_pixel(x, y, Rgb(components));
        }
    }

    image
}

/// The historical default seed used by the pipeline fixtures — keeps
/// generated bytes identical to the pre-`testutil` inline copies.
pub const FIXTURE_SEED: u32 = 0x1234_5678;

/// `deterministic_rgb_image` with the standard fixture seed.
pub fn fixture_rgb_image(width: u32, height: u32) -> RgbImage {
    deterministic_rgb_image(width, height, FIXTURE_SEED)
}

/// Smooth gradient with a light deterministic dither: compresses to the
/// "small but not tiny" JPEG range (a few tens of KB at moderate quality),
/// mimicking compact real-world scans for skip-heuristic tests. Reproducible
/// for a given `seed`.
pub fn gradient_rgb_image(width: u32, height: u32, seed: u32) -> RgbImage {
    let mut image = RgbImage::new(width, height);
    let mut state: u32 = seed;
    let band = (width / 32).max(1);

    for y in 0..height {
        for x in 0..width {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            let dither = ((state >> 28) & 0x7) as i32 - 4;
            let wave = ((x + y + (seed % 64)) / band) as i32 * 3;
            let components = [
                (128 + wave + dither).clamp(0, 255) as u8,
                (96 + wave / 2 + dither).clamp(0, 255) as u8,
                (160 + wave * 2 / 3 + dither).clamp(0, 255) as u8,
            ];
            image.put_pixel(x, y, Rgb(components));
        }
    }

    image
}

/// Encode an RGB image as JPEG with the image crate's built-in encoder.
pub fn encode_jpeg(image: RgbImage, quality: u8) -> Vec<u8> {
    let dynamic = DynamicImage::ImageRgb8(image);
    let mut cursor = Cursor::new(Vec::new());
    JpegEncoder::new_with_quality(&mut cursor, quality)
        .encode_image(&dynamic)
        .expect("failed to encode fixture JPEG");
    cursor.into_inner()
}
