// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	loadPresetUserConfig: () => typedError<PresetUserConfigPayload, AppErrorPayload>(__TAURI_INVOKE("load_preset_user_config")),
	savePresetUserConfig: (config: PresetUserConfigPayload) => typedError<PresetUserConfigPayload, AppErrorPayload>(__TAURI_INVOKE("save_preset_user_config", { config })),
	clearPresetUserConfig: () => typedError<null, AppErrorPayload>(__TAURI_INVOKE("clear_preset_user_config")),
	/**
	 *  Quick-mode (right-click) profile, persisted at the shared OS-config
	 *  location so the CLI's `quick` subcommand picks up GUI edits.
	 */
	loadQuickProfile: () => typedError<QuickProfilePayload, AppErrorPayload>(__TAURI_INVOKE("load_quick_profile")),
	saveQuickProfile: (profile: QuickProfilePayload) => typedError<QuickProfilePayload, AppErrorPayload>(__TAURI_INVOKE("save_quick_profile", { profile })),
	openPath: (path: string) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("open_path", { path })),
	revealPathInFolder: (path: string) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("reveal_path_in_folder", { path })),
	analyzePdf: (path: string | null, inputPath: string | null, password: string | null, onProgress: Channel<ProgressUpdate>) => typedError<AnalysisResponse, AppErrorPayload>(__TAURI_INVOKE("analyze_pdf", { path, inputPath, password, onProgress })),
	compressPdf: (request: CompressPdfRequest, onProgress: Channel<ProgressUpdate>) => typedError<CompressionResponse, AppErrorPayload>(__TAURI_INVOKE("compress_pdf", { request, onProgress })),
	compressScannedPdf: (request: CompressScannedPdfRequest_Deserialize, onProgress: Channel<ProgressUpdate>) => typedError<CompressionResponse, AppErrorPayload>(__TAURI_INVOKE("compress_scanned_pdf", { request, onProgress })),
	cancelCompression: (taskId: string) => typedError<null, AppErrorPayload>(__TAURI_INVOKE("cancel_compression", { taskId })),
	/**
	 *  Filter `paths` down to the ones that exist on disk. Used by the frontend
	 *  to pre-check a restored session queue instead of waiting for each missing
	 *  file to fail analysis.
	 */
	existingPaths: (paths: string[]) => typedError<string[], AppErrorPayload>(__TAURI_INVOKE("existing_paths", { paths })),
	appReady: () => typedError<null, AppErrorPayload>(__TAURI_INVOKE("app_ready")),
};

/* Types */
/**
 *  Wire types follow JSON/JS number semantics: byte sizes as `f64` (JSON
 *  numbers are doubles; exact up to 2^53) and counts as `u32`, because the
 *  TypeScript bindings forbid BigInt-style integers to avoid precision loss.
 */
export type AnalysisResponse = {
	fileSizeBytes: number | null,
	pageCount: number,
	imageObjectCount: number,
	documentKind: string,
	scannedConfidence: number | null,
	imageCoverage: number | null,
	estimatedSavingsPercent: number | null,
	recommendedPreset: string,
	maxImageEdgePx: number,
	recommendedMaxImageSizePx: number,
	recommendedImageQuality: number,
	isLikelyScanned: boolean,
	notices: BackendNotice[],
};

export type AppErrorPayload = {
	code: string,
	values: { [key in string]: string },
	fallback: string,
};

export type BackendNotice = {
	code: string,
	level: string,
	values: { [key in string]: string },
	fallback: string,
};

export type CompressPdfRequest = {
	path: string | null,
	inputPath: string | null,
	taskId: string | null,
	/**
	 *  Open password for encrypted PDFs. `None`/absent for plain files; a
	 *  wrong password fails with `error.wrongPassword`.
	 */
	password?: string | null,
	settings: CompressionSettingsPayload | null,
	preset: string | null,
	imageQuality: number | null,
	maxImageSizePx: number | null,
	optimizeImages: boolean | null,
	compressStreams: boolean | null,
	stripMetadata: boolean | null,
	removeMetadata: boolean | null,
	outputDir: string | null,
	/**
	 *  When set, the engine searches quality/edge parameters until the output
	 *  fits this byte budget (best effort otherwise).
	 */
	targetSizeBytes: number | null,
};

export type CompressScannedPdfRequest = CompressScannedPdfRequest_Serialize | CompressScannedPdfRequest_Deserialize;

export type CompressScannedPdfRequest_Deserialize = {
	path: string | null,
	inputPath: string | null,
	taskId: string | null,
	/**
	 *  Open password for encrypted PDFs — same semantics as
	 *  `CompressPdfRequest.password`.
	 */
	password?: string | null,
	settings: CompressionSettingsPayload | null,
	preset: string | null,
	imageQuality: number | null,
	grayscale: boolean | null,
	/**
	 *  Output codec for near-bilevel scanned images: `"jpeg"` (default) or
	 *  `"ccitt-g4"`.
	 */
	bilevelCodec?: string | null,
	stripMetadata: boolean | null,
	removeMetadata: boolean | null,
	outputDir: string | null,
	/**
	 *  When set, the engine searches quality/edge parameters until the output
	 *  fits this byte budget (best effort otherwise).
	 */
	targetSizeBytes: number | null,
} & {
	/**
	 *  Maximum image edge in pixels — same semantics as `CompressPdfRequest`.
	 *  (The historical `downsampleDpi`/`targetDpi` names were misnomers: the
	 *  value was always consumed as a pixel bound, not a DPI.)
	 */
	maxImageSizePx?: number | null,
} | {
	/**
	 *  Maximum image edge in pixels — same semantics as `CompressPdfRequest`.
	 *  (The historical `downsampleDpi`/`targetDpi` names were misnomers: the
	 *  value was always consumed as a pixel bound, not a DPI.)
	 */
	downsampleDpi?: number | null,
} | {
	/**
	 *  Maximum image edge in pixels — same semantics as `CompressPdfRequest`.
	 *  (The historical `downsampleDpi`/`targetDpi` names were misnomers: the
	 *  value was always consumed as a pixel bound, not a DPI.)
	 */
	targetDpi?: number | null,
};

export type CompressScannedPdfRequest_Serialize = {
	path: string | null,
	inputPath: string | null,
	taskId: string | null,
	/**
	 *  Open password for encrypted PDFs — same semantics as
	 *  `CompressPdfRequest.password`.
	 */
	password: string | null,
	settings: CompressionSettingsPayload | null,
	preset: string | null,
	imageQuality: number | null,
	/**
	 *  Maximum image edge in pixels — same semantics as `CompressPdfRequest`.
	 *  (The historical `downsampleDpi`/`targetDpi` names were misnomers: the
	 *  value was always consumed as a pixel bound, not a DPI.)
	 */
	maxImageSizePx: number | null,
	grayscale: boolean | null,
	/**
	 *  Output codec for near-bilevel scanned images: `"jpeg"` (default) or
	 *  `"ccitt-g4"`.
	 */
	bilevelCodec: string | null,
	stripMetadata: boolean | null,
	removeMetadata: boolean | null,
	outputDir: string | null,
	/**
	 *  When set, the engine searches quality/edge parameters until the output
	 *  fits this byte budget (best effort otherwise).
	 */
	targetSizeBytes: number | null,
};

export type CompressionResponse = {
	outputPath: string,
	originalSizeBytes: number | null,
	compressedSizeBytes: number | null,
	savedBytes: number | null,
	savingsPercent: number | null,
	elapsedMs: number,
	imagesRecompressed: number,
	imagesSkipped: number,
	imagesDeduplicated: number,
	streamsCompressed: number,
	metadataRemoved: boolean,
	outputWasSmaller: boolean,
	notices: BackendNotice[],
};

export type CompressionSettingsPayload = {
	preset: string | null,
	imageQuality: number | null,
	maxImageSizePx: number | null,
	optimizeImages: boolean | null,
	compressStreams: boolean | null,
	stripMetadata: boolean | null,
	/**  Re-encode color images as grayscale (best for black-and-white scans). */
	grayscale?: boolean | null,
	/**
	 *  Output codec for near-bilevel scanned images: `"jpeg"` (default) or
	 *  `"ccitt-g4"` (lossless ITU T.6, best for text scans).
	 */
	bilevelCodec?: string | null,
	/**  Shrink embedded Type0/CIDFontType2 TrueType fonts to the used glyphs. */
	subsetFonts?: boolean | null,
	/**
	 *  Convert CMYK images to RGB for re-encoding (default on since 0.8.0;
	 *  builds without the `cmyk-cms` feature keep CMYK untouched instead of
	 *  converting naively — grayscale requests still imply the collapse).
	 */
	cmykConversion?: boolean | null,
	outputDir: string | null,
};

export type PresetProfilePayload = {
	imageQuality: number,
	maxImageSizePercent: number,
	optimizeImages?: boolean | null,
	compressStreams?: boolean | null,
	stripMetadata?: boolean | null,
	grayscale?: boolean | null,
	/**  `"jpeg"` (default) or `"ccitt-g4"` for near-bilevel scans. */
	bilevelCodec?: string | null,
	subsetFonts?: boolean | null,
	/**  CMYK→RGB conversion for re-encoding (default on since 0.8.0). */
	cmykConversion?: boolean | null,
};

export type PresetUserConfigPayload = {
	version?: number,
	presets?: { [key in string]: PresetProfilePayload },
};

export type ProgressUpdate = {
	phase: string,
	percent: number | null,
	message: BackendNotice | null,
};

/**
 *  Persisted quick-mode (right-click) profile, edited from the desktop
 *  settings page and consumed by `pdf-compressor-cli quick`. Every field is
 *  optional — an explicit CLI flag wins first, then this profile, then the
 *  engine's built-in defaults.
 */
export type QuickProfilePayload = {
	version?: number,
	preset?: string | null,
	imageQuality?: number | null,
	maxImageSizePx?: number | null,
	optimizeImages?: boolean | null,
	compressStreams?: boolean | null,
	stripMetadata?: boolean | null,
	grayscale?: boolean | null,
	/**  `"jpeg"` (default) or `"ccitt-g4"` for near-bilevel scans. */
	bilevelCodec?: string | null,
	subsetFonts?: boolean | null,
	/**  CMYK→RGB conversion for re-encoding (default on since 0.8.0). */
	cmykConversion?: boolean | null,
	/**  Byte budget for target-size mode; absent means plain compression. */
	targetSizeBytes?: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

